default: &default
  adapter: postgresql
  encoding: unicode

  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: covid-19-live-count_development

test:
  <<: *default
  database: covid-19-live-count_test

production:
  <<: *default
  database: covid-19-live-count_production
  username: covid-19-live-count
  password: <%= ENV['COVID19_DATABASE_PASSWORD'] %>